version: '3.7'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    ports:
      - '27017:27017'
    expose:
      - '27017'
    environment:
      MONGODB_USER: ginioh
      MONGODB_PASSWORD: ginioh_fastify_test
    volumes:
      - mongodb_data_container:/data/db
      - ./mongo/init-script.js:/docker-entrypoint-initdb.d/initdb.js:ro
  app:
    container_name: app
    restart: always
    build: .
    image: 'fastify:1.0.0'
    links:
      - mongodb
    depends_on:
      - mongodb
    ports:
      - '3000:3000'
    expose:
      - '3000'
      

volumes:
  mongodb_data_container: null
